name: 'Post comment to pull request with its artifacts'
description: 'Post a comment in your PR with the artifacts download URLs'
inputs:
  prefix:
    description: Prefix message
    required: false
    default: ''
  suffix:
    description: Prefix message
    required: false
    default: ''
outputs:
  message:
    description: 'Comment message'
runs:
  using: 'node12'
  main: 'dist/index.js'
