name: 'Upload a post comment artifact'
on:
  pull_request:
    branches: [main]
jobs:
  push-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        id: upload
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
      - uses: ./
        needs: upload
        id: message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: Hallo
          suffix: Tschuss
      - name: comment PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.message.outputs.message }}
          check_for_duplicate_msg: true
